[package]
name = "chapter_checker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.12.5", features = ["json", "gzip"] }
regex = "1.10.6"
serde = { version = "1.0.206", features = ["derive"] }
serde_json = "1.0.124"
tokio = { version = "1.39.2", features = ["full"] }
futures = "0.3.30"
home = "0.5.9"
chrono = "0.4.38"
rand= "0.8.5"
